#!/bin/bash

##This is a little nasty hack to permanetly store DNS servers
##When an instance if created a file /etc/resolv.conf is created
##DNS servers set there are pointing to local addresses whcich,
##prevents us from accessing the web. However, this file is being
## built automatically on every system reboot, we add google's DNS
## servers to /etc/resolv.conf and than disable the auto build
## of that file so we can persist the changes.

sudo cat <<EOF > /etc/resolv.conf
; generated by /usr/sbin/dhclient-script
search openstacklocal
nameserver 8.8.8.8
nameserver 8.8.8.4
EOF

sudo echo "PEERDNS=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0
